language: objective-c
osx_image: xcode7.2
before_script:
- ./scripts/add-key.sh
script:
- xctool -project YouPlay-iOS.xcodeproj -scheme YouPlay-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES
after_success:
- ./scripts/archiv-and-deploy.sh
after_script:
- ./scripts/remove-key.sh
notifications:
  email: false
env:
  global:
  - APP_NAME = "YouPlay-iOS"
  - 'DEVELOPR_NAME = "iPhone Distribution: Shenzhen Sanliao Software Co.Ltd.(TJK5THP7XE)"'
  - PROFILE_NAME = "wujianguoAdHoc.mobileprovision"
before_install:
- openssl aes-256-cbc -K $encrypted_e2214e7c8d4d_key -iv $encrypted_e2214e7c8d4d_iv
  -in sanliaoDistribution.p12.enc -out sanliaoDistribution.p12 -d
- openssl aes-256-cbc -K $encrypted_e2214e7c8d4d_key -iv $encrypted_e2214e7c8d4d_iv
  -in wujianguoAdHoc.mobileprovision.enc -out wujianguoAdHoc.mobileprovision -d
