language: objective-c
osx_image: xcode7.2
before_script:
- security create-keychain -p travis ios-build.keychain
- security default-keychain -s ios-build.keychain
- security unlock-keychain -p travis ios-build.keychain
- security set-keychain-settings -t 3600 -u ios-build.keychain
- security import apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import sanliaoDistribution.cer -k ~/Library/Keychains/ios-build.keychain
  -T /usr/bin/codesign
- security import sanliaoDistribution.p12 -k ~/Library/Keychains/ios-build.keychain
  -P $KEY_PASSWORD -T /usr/bin/codesign
- mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
- cp ./wujianguoAdHoc.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
- security import wujianguo_development.cer -k ~/Library/Keychains/ios-build.keychain
  -T /usr/bin/codesign
- security import wujianguoDevelop.p12 -k ~/Library/Keychains/ios-build.keychain
  -P $KEY_PASSWORD -T /usr/bin/codesign
- cp ./wujianguoDev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
- echo "Add keychain to keychain-list"
- security find-identity -p codesigning ~/Library/Keychains/ios-build.keychain
- security list-keychains
- security list-keychains -s ios-build.keychain
script:
- xctool -project $APP_NAME.xcodeproj -scheme $APP_NAME -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- xcrun -log -sdk iphoneos PackageApplication "$PWD/build/Release-iphoneos/$APP_NAME.app" -o "$PWD/build/Release-iphoneos/$APP_NAME.ipa"
- curl -F "file=@$PWD/build/Release-iphoneos/$APP_NAME.ipa" -F "uKey=$PGYER_USER_KEY" -F "_api_key=$PGYER_API_KEY" http://www.pgyer.com/apiv1/app/upload

after_script:
- security delete-keychain ios-build.keychain
- rm -f ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_NAME.mobileprovision
notifications:
  email: false
env:
  global:
  - 'DEVELOPR_NAME = "iPhone Developer: estationwu@yeah.net (ZAKSP29RLG)"'
  - 'DEVELOPR_NAME_CO = "iPhone Distribution: Shenzhen Sanliao Software Co.Ltd.(TJK5THP7XE)"'
  - PROFILE_NAME = "wujianguoAdHoc.mobileprovision"
before_install:
- openssl aes-256-cbc -K $encrypted_e2214e7c8d4d_key -iv $encrypted_e2214e7c8d4d_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

branches:
  only:
    - release
