language: objective-c
osx_image: xcode7.2
before_script:
- "./scripts/add-key.sh"
script:
- xctool -project $APP_NAME.xcodeproj -scheme $APP_NAME -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY=$DEVELOPR_NAME PROVISIONING_PROFILE=$PROVISIONING_PROFILE_UUID
after_success:
- ./scripts/archiv-and-deploy.sh
after_script:
- ./scripts/remove-key.sh
notifications:
  email: false
env:
  global:
  - 'DEVELOPR_NAME = "iPhone Distribution: Shenzhen Sanliao Software Co.Ltd.(TJK5THP7XE)"'
  - PROFILE_NAME = "wujianguoAdHoc.mobileprovision"
before_install:
- chmod +x scripts/add-key.sh
- chmod +x scripts/archive-and-deploy.sh
- chmod +x scripts/remove-key.sh
- openssl aes-256-cbc -K $encrypted_e2214e7c8d4d_key -iv $encrypted_e2214e7c8d4d_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
