language: objective-c
osx_image: xcode7.2
before_script:
- openssl aes-256-cbc -K $encrypted_fb1e085703e6_key -iv $encrypted_fb1e085703e6_iv -in scripts/wujianguoAdHoc.mobileprovision.enc -out scripts/wujianguoAdHoc.mobileprovision -d
- openssl aes-256-cbc -K $encrypted_fb1e085703e6_key -iv $encrypted_fb1e085703e6_iv -in scripts/sanliaoDistribution.p12.enc -out scripts/sanliaoDistribution.p12 -d
script:
- xctool -project YouPlay-iOS.xcodeproj -scheme YouPlay-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES
after_success:
- ./scripts/archiv-and-deploy.sh
after_script:
- ./scripts/remove-key.sh
notifications:
  email: false
env:
  global:
  - APP_NAME = "YouPlay-iOS"
  - 'DEVELOPR_NAME = "iPhone Distribution: Shenzhen Sanliao Software Co.Ltd.(TJK5THP7XE)"'
  - PROFILE_NAME = "wujianguoAdHoc.mobileprovision"
