language: objective-c
osx_image: xcode7.2
before_script:
- security create-keychain -p travis ios-build.keychain
- security default-keychain -s ios-build.keychain
- security unlock-keychain -p travis ios-build.keychain
- security set-keychain-settings -t 3600 -u ios-build.keychain
- security import apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import sanliaoDistribution.cer -k ~/Library/Keychains/ios-build.keychain
  -T /usr/bin/codesign
- security import sanliaoDistribution.p12 -k ~/Library/Keychains/ios-build.keychain
  -P $KEY_PASSWORD -T /usr/bin/codesign
- mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
- cp ./wujianguoAdHoc.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
- security import wujianguo_development.cer -k ~/Library/Keychains/ios-build.keychain
  -T /usr/bin/codesign
- security import wujianguoDevelop.p12 -k ~/Library/Keychains/ios-build.keychain
  -P $KEY_PASSWORD -T /usr/bin/codesign
- cp ./wujianguoDev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
script:
- xctool -project $APP_NAME.xcodeproj -scheme $APP_NAME -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/archiv-and-deploy.sh
after_script:
- ./scripts/remove-key.sh
notifications:
  email: false
env:
  global:
  - 'DEVELOPR_NAME = "iPhone Developer: estationwu@yeah.net (ZAKSP29RLG)"'
  - 'DEVELOPR_NAME_CO = "iPhone Distribution: Shenzhen Sanliao Software Co.Ltd.(TJK5THP7XE)"'
  - PROFILE_NAME = "wujianguoAdHoc.mobileprovision"
before_install:
- openssl aes-256-cbc -K $encrypted_e2214e7c8d4d_key -iv $encrypted_e2214e7c8d4d_iv
  -in secrets.tar.enc -out secrets.tar -d
- chmod +x scripts/add-key.sh
- chmod +x scripts/archive-and-deploy.sh
- chmod +x scripts/remove-key.sh
- tar xvf secrets.tar
